<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resourses\Assets\money icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resourses\Assets\Capitalism.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resourses\Assets\money icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resourses\Styles\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoneyRec.Core\MoneyRec.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resourses\Assets\Capitalism.png" />
  </ItemGroup>

</Project>
